platform :ios, "6.0"

pod "SDWebImage"

pod "AFNetworking", "~> 2.0"

pod "YTKNetwork"

pod "Mantle"

pod 'MJRefresh'

pod 'SVProgressHUD'

pod 'INTULocationManager'

pod 'AMap2DMap'

pod 'AMapSearch'

pod 'GRMustache', '~> 7.3.2'
